data_dir: data
annotations:
  zip_url: http://images.cocodataset.org/annotations/annotations_trainval2017.zip
  zip_name: annotations_trainval2017.zip
  json_path: annotations/instances_train2017.json

target_categories: [3, 17, 18, 19]

splits:
  train: 0.8
  test: 0.19
  inference: 0.01

max_images: 5000
mask_area_threshold: 0.2
seed: 42
max_concurrency: 32

