name: segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pillow
  - numpy
  - pandas
  - matplotlib
  - opencv
  - tqdm
  - requests
  - aiohttp
  - pycocotools
  - omegaconf
  - plotly
  - scipy
  - pip:
      - torchvision
      - wandb
      - lmdb
      - dash
