# VisionSystem Model Config

backbone:
  img_size: 512
  patch_size: 4
  in_chans: 3
  embed_dim: 128
  depth: 3
  num_heads: 4
  window_size: 8

feature_project_dim: 1024

head:
  input_channels: [512, 512, 512]
  num_classes: 5
  d_model: 512
  num_queries: 100
  nhead: 4
  num_decoder_layers: 4
