# configs/train.yaml

# Model configuration
model:
  num_classes: 8
  inbuilt: False
  inference_prebuilt: True

# Training hyperparameters
training:
  epochs: 100
  batch_size: 8
  eval_freq: 5
  learning_rate: 1e-5
  optimizer: "adamw"
  scheduler: "step"
  step_size: 20
  gamma: 0.5
  eos_coef: 0.1
  weight_aux: 0.5
  weight_decay: 1e-3
  weight_mask_bce: 1.0
  weight_ce: 1.0
  weight_dice: 1.0
  warmup: true
  warmup_epochs: 5
  clipping: true
  max_norm: 1.0
  sample_points: 128

# Dataset and DataLoader settings
dataset:
  data_yaml: "configs/dataset.yaml"
  base_input: "run/data/prepared"
  base_output: "run/data/lmdb"
  train_image_lmdb: "run/data/lmdb/train_images.lmdb"
  train_mask_lmdb: "run/data/lmdb/train_masks.lmdb"
  test_image_lmdb: "run/data/lmdb/test_images.lmdb"
  test_mask_lmdb: "run/data/lmdb/test_masks.lmdb"
  transform_size: [224, 224]

# Paths for saving logs and results
paths:
  weights_path: "run/data/prepared/train/class_weights.pt"
  train_mask_dir: "run/data/prepared/train/masks"
  checkpoint_dir: "run/logs/checkpoints"
  output_checkpoint: "run/logs/checkpoints/latest.pth"
  output_inference_model: "run/logs/checkpoints/model.pth"
  results_dir: "run/logs/results"
  model_config: "configs/model.yaml"

# Hardware optimization and resource settings
hardware:
  device: "cuda:0"
  use_amp: true
  num_workers: 4
  pin_memory: true

# Logging configuration (using wandb, if enabled)
logging:
  use_wandb: true
  wandb_project: "segmentation_project"
  wandb_dir: "run/wandb"
  print_log_freq: 100
  image_log_freq: 1000
  wandb_log_freq: 10
